### ISSUE TITLE
A related side (OSX) request

### ISSUE THREAD

**Issue by japush** [0xbb/gpu-switch#1]
Hi Bruno,

I am one of 33K+ 2011 Macbook Pro users with the unfortunate discrete GPU heat-induced solder connection failure. The MBP will always boot OSX in the single user mode, but unless all ATI/AMD GPU kexts are removed from ~/system/library/extensions/  folder, the MBP will freeze during normal OSX boot. 

The brute removal of ATI/AMD GPU kexts causes the system to behave very slow, with graphic artifacts etc. 
Based on your project, did you by chance find a way to disable initiation of the discrete GPU  and boot OSX in such a way as if only Intel GPU was present? I know you are working on Linux, but if you know how to achieve this in OSX, great many people will be grateful to you. Please share what you know or think.
Thank you!

japush

**Comment by 0xbb** [comment]
Hi japush!
I also haven seen your issues at this thread: https://github.com/ah-/gmux-scripts/issues/1#issuecomment-69776789
I will try to help you.
Did you tried solving the issue with  gfxcardstatus 2.2.1 (exact version is important)?
- Boot in OSX with Kexts remove
  - Select gfxCardStatus -> dedicated only.
  - Reboot
  - Results ?

Bruno

**Comment by japush** [comment]
Hi Bruno,
Thank you for trying to help! Of course, I tried that.  Once I remove
AMD/ATI\* kexts,  no matter what gfxCardStatus version (2.2.1 or the new
one) I try,  it will NOT let me select integrated graphics, claiming the
dependency 'External Display'. Of course there is no external display and
the graphics are in fact handled by integrated gpu, but that's the
paradoxical way my system behaves with those Kexts removed.
Any other ideas to get the system to work entirely off integrated gpu while
the kexts are intact?
Thanks again!

**Comment by 0xbb** [comment]
Hi japush,
I would  ask the developer of gfxCardStatus for help.
If anyone knows about your "External Display" problem then him. If you can't switch between the GPUs via gfxCardStatus I am also out of ideas how to force the usage of the internal GPU.
