### ISSUE TITLE
It worked but the CPU usage is constantly 10%

### ISSUE THREAD

**Issue by myonlylonely** [0xbb/gpu-switch#12]
CPU has a constant load of about 10% on the system, from the System process after successfully using this patch. I Googled there were a lot of guys facing the same problem but no answers. Is there a solution to this bug? Some people said make macbook sleep and wake it up again solved the problem. I tried this 'solution', the CPU usage is normal but macbook uses NVidia card again (As a second Display and can't switch it to the first display again).

**Comment by 0xbb** [comment]
I guess you are using Window? I can really help you with that, because I seems to be something related with the Intel Windows driver.

**Comment by myonlylonely** [comment]
Yes, I'm using Windows 10. So there is no solution to this for now?

**Comment by 0xbb** [comment]
Not of any that I am aware of.
You can also contact the people in this thread: https://github.com/0xbb/gpu-switch/issues/5
