### ISSUE TITLE
Macbook Pro 9,1 - Error when running bat

### ISSUE THREAD

**Issue by ReevMich** [0xbb/gpu-switch#14]
After running the .bat file in Admin mode this the error i get on Windows 10 64bit

C:\Users\El Capitan\Desktop\gpu-switch-windows\gpu-switch>gpu-switch.exe -i
Switching: to integrated GPU
Switching: Error
Error code was: 1
Error message was: Incorrect function.

C:\Users\El Capitan\Desktop\gpu-switch-windows\gpu-switch>pause
Press any key to continue . . .

**Comment by 0xbb** [comment]
I think your Windows is not booted in UEFI mode.
See here: https://github.com/0xbb/gpu-switch/issues/8#issuecomment-127398240
