### ISSUE TITLE
MacBookPro 6,2 Windows 10 question.

### ISSUE THREAD

**Issue by steppenx** [0xbb/gpu-switch#17]
I initially stumbled across this site while looking for solutions to switch to intrigued graphics while running Windows 7 on my mac because it seems my nVidia GPU is failing.  The driver crashes anytime I run a graphic intensive program (even Chrome), screen goes black for a bit then I get an error telling me the graphics card timed out and failed.  Can't play any games because of the same issue.  I have GFXCardStatus installed on my mac side(OSX 10.10.5) and that seems to work so I was looking for a similar solution for the windows side.

I upgraded to Windows 10 as I read that this fix will only work with Windows 8/10.

However I am having an issue getting the gpu to switch on Windows 10 with my MacBookPro 6,2.  I can run the exe without errors, but when i try and run one of the .bat files I get an error that says it could not complete due to "error 1".  Any idea why this is occurring?

One thing to add, in the windows how to section is says to check "Windows is using the MacBook's UEFI mode"  my BIOS is listed as "legacy" not UEFI.  How do I get it to run UEFI under Windows 10?  Also I attempted to install the apple_set_os.efi even though this was for 11,3 MacBook Pros and while refind can recognize it on bootup it gives me an error saying it failed to run as well.  Any ideas would be great, thank you!

**Comment by steppenx** [comment]
Just noticed this issue was almost the same as other one posted on here, seems I have to install windows without EFI emulation or natively to avoid installing it with the legacy bios.  Is the author sure that they only way to get this fix to work is to reinstall windows? That seems like a pretty excessive fix...

**Comment by 0xbb** [comment]
Hi @steppenx, gpu-swich is purely based on writing values to a special EFI variable. So there is no way around of installing a UEFI based Window.
