### ISSUE TITLE
EFI mode

### ISSUE THREAD

**Issue by akhats** [0xbb/gpu-switch#20]
I have Macbook Pro 8,2 (Early 2011) and I want to boot it using the integrated intel graphics. Whenever I try to run "./gpu-switch -i" as a root I get "Fatal: gpu-switch has to be run in EFI mode."

Please let me know how can get to EFI mode.
Thanks

**Comment by 8a5** [comment]
I have the same problem when using this on Macbook Pro 11,3
Even though Mac is installed as EFI

**Comment by pierremoreau** [comment]
Assuming you are running Linux, you could have a look at the wiki entry about UEFI from Arch: https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface. Even if you are not using Arch Linux as your distribution, most of the information should apply to other distributions as well.

**Comment by alexdclark** [comment]
My discrete graphics called just died in my 2011 15" MBP and I'm trying to use this tool to go to the Integrated Graphics by default even when its booting. I'm getting this same error I'm not sure whether my Mac is installed in "EFI" its just a normal OS X setup. Any idea?

**Comment by SnakeO** [comment]
Ditto: http://imgur.com/a/Yqsok

**Comment by 0xbb** [comment]
I assume you are trying to switch between GPUs under OS X.
Simply  using the Linux script won't help you there.

You have to checkout the osx folder and follow the instructions here: https://github.com/0xbb/gpu-switch#os-x-usage

**Comment by neutral888** [comment]
Hey all,

I am trying to switch to iGPU in osx:

I ran build.sh and it says: 

=== BUILD TARGET gpu-switch OF PROJECT gpu-switch WITH CONFIGURATION Release ===
build successfull: ..

so after this I run /.gpu-switch -i and I get the same response @akhats @8a5 @SnakeO 

Fatal: gpu-switch has to be run in EFI mode.

How do switch it to iGPU (please) @0xbb, what am I not doing correctly ?

**Comment by 0xbb** [comment]
Could you provide the output of the command ``file ./gpu-switch``.
I think you are still running the Linux script.

**Comment by 0xbb** [comment]
You probably need to ``cd`` into the build folder.

**Comment by neutral888** [comment]
From the /osx/build folder I run ./gpu-switch and it gives:

2017-02-24 00:11:35.643 gpu-switch[1646:43841] gpu switch usage:
	-i	 switch to integrated
	-d	 switch to discrete
	 -a	 enable auto switching
	-h/--help display this usage information.

**Comment by neutral888** [comment]
OK! I ran ./gpu-switch -i from the build folder and it worked!

Please tell me how I can make it do this every time I log out of osx?

**Comment by 0xbb** [comment]
There is ``install_hooks.sh`` script plus a hooks folder in the osx folder. Here also my support ends.
