### ISSUE TITLE
Proprietary nvidia drivers

### ISSUE THREAD

**Issue by isaksamsten** [0xbb/gpu-switch#21]
Hi!

Since switching monitors with the nouveau driver is problematic, I've tried using the proprietary nvidia driver. Unfortunately, this disables the vgaswitcheroo method of shutting of the discrete (or the integrated) graphics card.

Have you had any success getting the discrete card to switch off using these drivers?

**Comment by 0xbb** [comment]
Hi!
I never had any sucess of swichting off the dGPU/iGPU with the proprietary Nvidia drivers.
