### ISSUE TITLE
MacBook Pro 11,5 Retina

### ISSUE THREAD

**Issue by ghost** [0xbb/gpu-switch#25]
Wanted to inform you that [MacBook Pro 11,5](http://www.everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.5-15-dual-graphics-mid-2015-retina-display-specs.html) with AMD + Intel GPU works with 

> spoof_osx_version

**Comment by 0xbb** [comment]
Thank you!
I added your test result.
