### ISSUE TITLE
How to install gpu-switch on macbook

### ISSUE THREAD

**Issue by neutral888** [0xbb/gpu-switch#33]
Hi all,

How do I install and load gpu-switch on the mac?

I downloaded and unzipped the gpu-switch-master.zip
Now can someone please tell me how to install and switch to integrated card?

It is unzipped to /Downloads/gpu-switch-master

Many thanks

**Comment by neutral888** [comment]
I was able to build build.sh by typing : sh build.sh
then it said "build successful"

Then when I type ./gpu-switch -i  it gives the reply of : Fatal: gpu-switch has to be run in EFI mode.

What does this mean please @0xbb and how can I switch to integrated card?

Thanks

**Comment by alien45** [comment]
Having the same issue here. Any solution @0xbb?

**Comment by 0xbb** [comment]
You have to checkout the osx folder and follow the instructions here: https://github.com/0xbb/gpu-switch#os-x-usage

**Comment by 0xbb** [comment]
(Make sure you run ./gpu-switch from the osx folder)

**Comment by arkitekt-dev** [comment]
No executable is created in the build folder even after build.sh says "build successful". 
2011 late.
10.10.5.
