### ISSUE TITLE
Broken since I updated to OS X 10.12.4

### ISSUE THREAD

**Issue by soundg33k** [0xbb/gpu-switch#37]
MacBook Pro 11.5 
OS X 10.12.4

I ran "gpu-switch -i" on my ubuntu partition and ended up with having to reset the nvram on my MacBook, otherwise any OS trying to use the discrete gpu would hang.

I have done it twice... because the first time I was not sure it was the cause. It use to be working before the update to OS X 10.12.4

**Comment by robertdoleson** [comment]
MacBook Pro 11.3
OS X 10.12.4

I am also experiencing this same problem. gpu-switch with Windows worked fine before updating to 10.12.4.

**Comment by 0xbb** [comment]
Thanks for your reports.
It's going to be problematic to fix this issue, because I don't have access to any MacBook anymore.

**Comment by robertdoleson** [comment]
For me, it ended up being an issue with apple_set_os.efi. 

[https://egpu.io/forums/mac-setup/how-to-keep-mbps-irisiris-pro-activated-when-booting-into-windows-boot-camp/](url)

Working fine now.

**Comment by soundg33k** [comment]
Not sure if I trust the link in question... it would be nice if they could post the source code for their fix... or better fork the this github repo!

The executable they provide is 290kB and the one I compile is 4kB... no way I am installing that on my machine.

**Comment by 0xbb** [comment]
Could you email me their binary? I am sure that I can quickly extract the fix.

**Comment by soundg33k** [comment]
I just sent the binary I downloaded from the thread by email to you.

I looked at the hexdump of the binary. The strings seems to be the same, so I don't know exactly what they done. I was hoping to find that they change the only change the following string "Mac OS X 10.9"... but it does not seems to be the case.

**Comment by 0xbb** [comment]
This was caused by https://github.com/0xbb/apple_set_os.efi/issues/4
Thanks @soundg33k for helping me finding this bug and I published a fix there.

**Comment by ah-** [comment]
Nice!
