### ISSUE TITLE
Fatal: Couldn't mount '/sys/firmware/efi/efivars'.

### ISSUE THREAD

**Issue by eirpilk** [0xbb/gpu-switch#4]
**mount: unknown filesystem type 'efivarfs'**
**Fatal: Couldn't mount '/sys/firmware/efi/efivars'.**

Using Linux (Debian Wheezy)
It worked before I used the patch apple_set_os.efi which enabled the iGP.

Now it throws this error when I try to execute:
./gpu-switch -i
./gpu-switch -d

Any possible solution?

**Comment by ah-** [comment]
Hi,

Can you check if CONFIG_EFIVAR_FS=y is enabled in your kernel config? You can get the config from /proc/config.gz.

Could you check if it starts working again if you remove apple_set_os.efi?

**Comment by 0xbb** [comment]
Hi!
I think you didn't boot Linux in EFI mode.
Can you check if ``efivar -l`` give you any output?

**Comment by eirpilk** [comment]
ah-: I see no file like config.gz in /proc/, see below

0xbb:

$ efivar -l
bash: efivar: command not found

I am using TAILS os.
Using grub.cfg from project here on GIT (I see your activity in it)

which gives grub this configuration:
* = Added according to your instructions on apple_set_os.efi

set timeout=30
set default=0

menuentry "TAILS live" {
	*chainloader /EFI/BOOT/custom/apple_set_os.efi
	*boot #added by me
	fakebios
	search --set -f /live/vmlinuz
	linux /live/vmlinuz askmethod boot=live config live-media=removable nopersistent noprompt timezone=Etc/UTC block.events_dfl_poll_msecs=1000 splash nox11autologin module=Tails quiet
	initrd /live/initrd.img
}

Both graphic proccessors are now powered and active. However I see no way to disable discrete one (enable only integrated).

**Comment by eirpilk** [comment]
Sorry for confusing post.
using grub.cfg from **TAILS-OSX** (here on git)

**Comment by ah-** [comment]
Seems /proc/config.gz doesn't exist in Debian/TAILS, can you have a look at ls /boot/config-$(uname -r)?

And maybe put your dmesg up as a gist?

**Comment by 0xbb** [comment]
I gave it a try and was successful with booting the amd64 version of Tails (vmlinuz2) and removing ``fakebios`` from the ``grub.cfg``:
```
menuentry "TAILS live" {
        chainloader /EFI/BOOT/custom/apple_set_os.efi
        boot
        search --set -f /live/vmlinuz2
        linux /live/vmlinuz2 askmethod boot=live config live-media=removable nopersistent noprompt timezone=Etc/UTC block.events_dfl_poll_msecs=1000 splash nox11autologin module=Tails  quiet
        initrd /live/initrd2.img
}
```

**Comment by eirpilk** [comment]
Thanks. That did the trick to be able to apply ./gpu-switch (-i/-d)

However, it takes no effect. Since I need to reboot to apply the changes, and Tails is running in RAM (no connection between running instances.)

Would it be possible to make the ./gpu-switch -i/-d somehow permament?
Because right now there are 2 graphic processors running.

[lspci -v | grep VGA]
00:02.0 VGA compatible controller: Intel Corporation Crystal Well Integrated Graphics Controller (rev 08) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller: NVIDIA Corporation Device 0fe9 (rev a1) (prog-if 00 [VGA controller])

**Comment by eirpilk** [comment]
Or I was thinking to prompt it at the very boot time. (Hardcore it somehow into the Tails os.) So that we could simulate the needed reboot to take effect.

**Comment by ah-** [comment]
It should be permanent, gpu-switch only writes a firmware variable that sets the primary gpu from the next boot on. This doesn't power down anything yet, it just selects whether your xorg runs with the Intel or Nvidia gpu.

Can you check whether your xorg runs with the Intel gpu after a gpu-switch -i and then a reboot?

Once that works you can have a look at turning the Nvidia GPU off using vga_switcheroo: echo OFF > /sys/kernel/debug/vgaswitcheroo/switch

**Comment by eirpilk** [comment]
I see. The issue is there isn't vgaswitcheroo in Tails OS.
I am looking for a way to permanently power down Nvidia GPU.

I am sorry to misunderstood the real purpose of the GPU-Switch tool.

**Comment by ah-** [comment]
I thought the debian kernel included vgaswitcheroo? What does "grep -i switcheroo /boot/config-`uname -r`" say?

Maybe it's just not initializing properly, if you post your dmesg I'll have a look.

Yeah, the situation is a bit complicated at the moment, there were promising patches for proper switching on the dri-devel mailing list just a few days ago, maybe it improves soon. For now you can switch to Intel with gpu-switch, but to turn off the Nvidia gpu you need vgaswitcheroo.

**Comment by 0xbb** [comment]
I did a small test and I succeeded to turn off the Nvidia GPU!
It turned out that Tails is just not mounting the debugfs.

I used this commands to turn the discrete GPU off: 
```
mount -t debugfs none /sys/kernel/debug
echo OFF > /sys/kernel/debug/vgaswitcheroo/switch
```

**Comment by eirpilk** [comment]
From now on you are the [HERO] number [ONE] for me.

I was trying to figure this out for more than a month and a half.

You bring all this so flawlessly.

Thank you a milion. Really. Believe that this will and may help even more people.
Time to bring it to the light.

- I am out guys. Gonna sleep on the laptop tonight. Because it will last that long.
No more baked hotdogs on the case, no more extra chargers to make it stand.

0xbb saved this day.

You man. You just broke biggest stone I had above my head in the past time.
In few days and few replies.

Thank you so much.
Never gonna forget You and Your work.

Live a great life.

Really.

**Comment by 0xbb** [comment]
Haha, thank you :). Don't forget ah-, he discovered most of these tricks!

**Comment by eirpilk** [comment]
This issue is closed. May be used for other as a resource how to:

### ENABLE IGP (INTEL IRIS PRO) ON MACBOOK PRO (RETINA)

**Tails:**

Get patch from the guy(s?) above called **[apple_set_os.efi](https://github.com/0xbb/apple_set_os.efi)**

Get **[grub.cfg](https://github.com/hellais/TAILS-OSX)**
*[example configuration above, may depend slightly whether you want to enable apparmor as well]*

Copy both of the files into:
`cp apple_set_os.efi /EFI/BOOT/custom/`
`cp grub.cfg /EFI/BOOT/`

[on your Tails stick. Not running one.]

Boot.

Enjoy your integrated graphic card.
[If powered off Nvidia] Enjoy longer batter life.

**Other linux distro:**
may depend, but probably same procedure with grub and apple_set_os.efi

### DISABLE DISCRETE NVIDIA GPU

`mount -t debugfs none /sys/kernel/debug [IF USING TAILS]`
`echo OFF > /sys/kernel/debug/vgaswitcheroo/switch`

___________________________________________________
ALL THAT THANKS TO THE GUYS ABOVE. **0XBB** & **AH-**. PRAISE THEM.
