### ISSUE TITLE
Couldn't mount 'efivarfs' on Linux

### ISSUE THREAD

**Issue by yesorz** [0xbb/gpu-switch#51]
When I try the command 'sudo ./gpu-switch -i', the following error shows up:

mount: /sys/firmware/efi/efivars: unknown filesystem type 'efivarfs'.
Fatal: Couldn't mount '/sys/firmware/efi/efivars'.

I am using MacBookPro 15,1 (Mid 2018), already tried using apple_set_os.efi / spoof_os_version = 10.9 under rEFInd

Would be really appreciated if someone can help.

**Comment by cristianmiranda** [comment]
I'm having exactly the same issue. I'm able to see the Intel card using refind, but can't use gpu-switch to make it effective.
Any updates on this?

**Comment by Redecorating** [comment]
you probably have `efi=noruntime` as a kernel parameter. This disables efi runtime services such as nvram, as one runtime call used for nvram writes is broken on T2 Macs. This patch fixes that issue, so `efi=noruntime` is no longer needed to prevent nvram writes, as they won't cause crashes anymore. https://lore.kernel.org/all/20220112101413.188234-1-ardb@kernel.org/

**Comment by yesorz** [comment]
thanks @Redecorating 
I'm now using your t2 arch wifi-iso, it works perfectly!
(though i know this recent kernel fix is commonly adopted.)
Closing this ticket as Resolved.
