### ISSUE TITLE
Windows 7 64-bit compatibility

### ISSUE THREAD

**Issue by AggressiveNapkin123** [0xbb/gpu-switch#6]
Hey, thanks for taking the time to work this out!

I'm new to Unix and to Bootcamp. My MBP (Mid 2014) is my first Mac, but like a lot of other new and old users of MBP's, I'm trying to get the switchable graphics working under Bootcamp.

I have successfully gotten Windows 7 (64-bit) installed through Bootcamp, installed rEFInd with apple_set_os.efi in the EFI partition, and can boot into Windows 7 in Safe Mode and see two graphics adapters. And like many others, if I boot into Windows 7 not in Safe Mode, I see the Windows boot logo animate, followed by a black screen and no login jingle.

Using the gpu-switch batch files to solve this issue, though, isn't possible as Windows spits back an error telling me it isn't compatible with 64-bit operating systems. I can't seem to find any compatibility mode to circumvent the issue.

Is that error actually meaningful or is it a sign that the method is simply untested on Windows 7? I don't have a copy of Windows 8 lying around, nor a 32-bit copy of Windows 7 to troubleshoot the problem any further. Please forgive me if the solution is lying right under my nose. I'm so close to getting this working, so please let me know how I can help you in figuring this out!

**Comment by 0xbb** [comment]
Hi,
sorry for the late response.

Did you start apple_set_os.efi every time before you boot Windows?

Your error message doesn't make much sense to me, but you could try this new build https://github.com/0xbb/gpu-switch/releases/tag/static-test ?

**Comment by AggressiveNapkin123** [comment]
Oof, sorry for MY late response!

I did, indeed, start apple_set_os.efi every time before boot. I'm really busy right now and will try your new build when I get a chance - I just wanted to respond letting you know I had seen your response and am still interested in solving the problem!

Thanks!
