### ISSUE TITLE
Windows 10 Compatibility

### ISSUE THREAD

**Issue by Emptyless** [0xbb/gpu-switch#8]
When using the Integrated.bat or Dedicated.bat  files it gives the warning: 

The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem. 

I know the program is created for Windows 8 but thought i post it here for future reference, are there any plans on upping the compatibility for Windows 10?

**Comment by 0xbb** [comment]
Hi,
I think you need to install [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-US/download/details.aspx?id=40784) to resolve this error.
People have been running it successfully under Window 10 here: https://github.com/0xbb/gpu-switch/issues/5

**Comment by Emptyless** [comment]
I have installed Visual C++, it was a solution mentioned in other threads as well. But it did not give me the required .dll

Searching my computer using the new search feature yields the same result, or in other words no result. It does however find MSVCR110.dll when i start typing so i think it really isn't installed. I'll try to find a solution for more people like me since this does not seem to be an issue caused by your program or Windows. 

Thanks for the really really fast reply!

**Comment by Emptyless** [comment]
The required .DLL is already installed but not recognized by the .bat even when running as administrator. 
What could cause this? 

The folder with the required .dll
http://i.imgur.com/jMGTCIB.png

The error:
http://i.imgur.com/bapNMwO.png

edit:

to add to this: copying the MSVCR120.dll to the same folder as gpuswitch results in this error:
http://i.imgur.com/LVZj4IY.png

**Comment by 0xbb** [comment]
Thanks for the screenshots.
Could you please try this binary: https://github.com/0xbb/gpu-switch/releases/download/static-test/gpu-switch.exe ?

**Comment by Emptyless** [comment]
I ran it and opened it as administrator. It flashed-closed a program but i did not get an error nor a screen telling me what happend. Was that intended behaviour?

**Comment by 0xbb** [comment]
Did you run it by replacing the old exe and launching one of the bat files?

**Comment by Emptyless** [comment]
Excuse me i did not. I have replaced the previous  gpuswitch and am getting this command prompt result now, I have also installed the x86 visual studio drivers in the mean time even though my computer is 64 bit. This might also explain it but still an error:

http://i.imgur.com/kSxQNq5.png

**Comment by 0xbb** [comment]
OK, it would be still good to know if it works now works without the Visual C++ Redistributable.

Did you boot Windows in UEFI mode?
Could you check it like described here: http://blogs.technet.com/b/home_is_where_i_lay_my_head/archive/2012/10/02/how-to-check-in-windows-if-you-are-using-uefi.aspx ?

**Comment by Emptyless** [comment]
BIOS Mode: Legacy, it is different from UEFI i guess. Do i need to use rEFInd to boot in UEFI? I have placed the apple_set_os in a EFI/custom and booted once but it gave me a black screen. So i started up mac os and used the settings -> startupdisk to boot into Windows again

**Comment by 0xbb** [comment]
You don't need rEFInd to boot Windows via UEFI, but apple_set_os.efi has to be run every time before you boot Windows.

Nevertheless switching between the GPUs only works when Windows is installed without the BIOS emulation, because the MacBook's firmware always turns off the iGPU when the emulation is used.

There are some guides on the Internet how to install Window 8 on an MacBook with native UEFI booting. Maybe there is also a way of converting your exiting installation, but I am not sure about that.

**Comment by Emptyless** [comment]
Thank you very much for all your help! Then i know the problem now. I will be looking into installing it natively!

**Comment by kuncevic** [comment]
Experiencing the inability to change the brightness when switched to integrated on W10.

**Comment by 8a5** [comment]
I have this same problem. I have  Visual C++ Redistributable Packages for Visual Studio 2013 installed, msvcr120.dll is inside system32 folder. Windows 10 UEFI. 

How to fix this, can you help?

**Comment by tuotuoZ** [comment]
install the x86 version helped me!
