### ISSUE TITLE
FYI: A refind patch which calls apple_set_os

### ISSUE THREAD

**Issue by orospakr** [0xbb/gpu-switch#9]
I wrote this last summer to avoid doing chainloading shenanigans with GRUB and refind (or using the EFI executable utility).  I have a 10,1 (not realizing that, apparently, this hack is only needed on 11,x?).

I figured I'd share it with you guys!

https://github.com/orospakr/refind

**Comment by 0xbb** [comment]
Hey orospakr ,
thanks for sharing your repository with us.
I added your repo to the list of possible apple_set_ost tricks.

I am not aware that the 10,x model needs the apple_set_os hack. I don't think that this model hides the iGPU if Linux is booted in EFI mode.
